version: '3'
services:
  database:
    container_name: database
    image: postgis/postgis:13-master
    volumes:
      - ./data/database:/var/lib/postgresql/data
    networks:
      - directus
    environment:
      POSTGRES_USER: 'directus'
      POSTGRES_PASSWORD: 'directus'
      POSTGRES_DB: 'directus'

  cache:
    container_name: cache
    image: redis:6
    networks:
      - directus

  directus:
    container_name: directus
    image: directus/directus:latest
    ports:
      - 8055:8055
    volumes:
      # By default, uploads are stored in /directus/uploads
      # Always make sure your volumes matches the storage root when using
      # local driver
      - ./uploads:/directus/uploads
      # Make sure to also mount the volume when using SQLite
      # - ./database:/directus/database
      # If you want to load extensions from the host
      # - ./extensions:/directus/extensions
    networks:
      - directus
    depends_on:
      - cache
      - database
    environment:
      KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
      SECRET: '6116487b-cda1-52c2-b5b5-c8022c45e263'

      # Variable Description Default Value
      # DB_CLIENT Required. What database client to use. One of pg or postgres, mysql, oracledb, mssql, or sqlite3. --
      # DB_HOST Database host. Required when using pg, mysql, oracledb, or mssql. --
      # DB_PORT Database port. Required when using pg, mysql, oracledb, or mssql. --
      # DB_DATABASE Database name. Required when using pg, mysql, oracledb, or mssql. --
      # DB_USER Database user. Required when using pg, mysql, oracledb, or mssql. --
      # DB_PASSWORD Database user's password. Required when using pg, mysql, oracledb, or mssql. --
      # DB_FILENAME Where to read/write the SQLite database. Required when using sqlite3. --
      # DB_CONNECTION_STRING When using pg, you can submit a connection string instead of individual properties. Using this will ignore any of the other connection settings. --
      # DB_POOL_* Pooling settings. Passed on to the tarn.js (opens new window)library. --
      # DB_EXCLUDE_TABLES CSV of tables you want Directus to ignore completely spatial_ref_sys,sysdiagrams
      # DB_CHARSET Charset/collation to use in the connection to MySQL/MariaDB UTF8_GENERAL_CI
      # DB_VERSION Database version, in case you use the PostgreSQL adapter to connect a non-standard database. Not normally required. --

      DB_CLIENT: 'pg'
      DB_HOST: 'database'
      DB_PORT: '5432'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: 'mauro.longano@marconirovereot.it'
      ADMIN_PASSWORD: 'd1r3ctu5'

      # Make sure to set this in production
      # (see https://docs.directus.io/reference/environment-variables/#general)
      # PUBLIC_URL: 'https://directus.example.com'

networks:
  directus:

